#!/bin/bash

hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleEG-Run2016B-23Sep2016-v3.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleEG-Run2016B-23Sep2016-v3/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleEG-Run2016C-23Sep2016-v1.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleEG-Run2016C-23Sep2016-v1/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleEG-Run2016D-23Sep2016-v1.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleEG-Run2016D-23Sep2016-v1/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleEG-Run2016E-23Sep2016-v1.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleEG-Run2016E-23Sep2016-v1/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleEG-Run2016F-23Sep2016-v1.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleEG-Run2016F-23Sep2016-v1/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleEG-Run2016G-23Sep2016-v1.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleEG-Run2016G-23Sep2016-v1/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleEG-Run2016H-PromptReco-v2.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleEG-Run2016H-PromptReco-v2/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleEG-Run2016H-PromptReco-v3.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleEG-Run2016H-PromptReco-v3/ | grep ".root"`;


hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleMuon-Run2016B-23Sep2016-v3.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleMuon-Run2016B-23Sep2016-v3/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleMuon-Run2016C-23Sep2016-v1.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleMuon-Run2016C-23Sep2016-v1/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleMuon-Run2016D-23Sep2016-v1.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleMuon-Run2016D-23Sep2016-v1/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleMuon-Run2016E-23Sep2016-v1.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleMuon-Run2016E-23Sep2016-v1/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleMuon-Run2016F-23Sep2016-v1.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleMuon-Run2016F-23Sep2016-v1/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleMuon-Run2016G-23Sep2016-v1.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleMuon-Run2016G-23Sep2016-v1/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleMuon-Run2016H-PromptReco-v2.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleMuon-Run2016H-PromptReco-v2/ | grep ".root"`&
hadd root://cmseos.fnal.gov//store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/ljmet_trees/ljmet_FakeRate_DoubleMuon-Run2016H-PromptReco-v3.root `xrdfs root://cmseos.fnal.gov ls  -u /eos/uscms/store/user/lpctlbsm/clint/FakeRate/25ns/Jan09/DoubleMuon-Run2016H-PromptReco-v3/ | grep ".root"`;

