import FWCore.ParameterSet.Config as cms

TopElectronSelector = cms.PSet(version            = cms.string("TIGHT"),
                   	       deta_EB		  = cms.double(0.0095),
                   	       dphi_EB		  = cms.double(0.0291),
                   	       sihih_EB		  = cms.double(0.0101),
                   	       hoe_EB		  = cms.double(0.0372),
                   	       d0_EB		  = cms.double(0.0144),
                   	       dZ_EB		  = cms.double(0.323),
                   	       ooemoop_EB	  = cms.double(0.0174),
                   	       reliso_EB	  = cms.double(0.0468),
                   	       deta_EE		  = cms.double(0.00762),
                   	       dphi_EE		  = cms.double(0.0439),
                   	       sihih_EE		  = cms.double(0.0287),
                   	       hoe_EE		  = cms.double(0.0544),
                   	       d0_EE		  = cms.double(0.0377),
                   	       dZ_EE		  = cms.double(0.571),
                   	       ooemoop_EE	  = cms.double(0.01),
                   	       reliso_EE	  = cms.double(0.0759),
			       mHits_EB		  = cms.int32(2),
			       mHits_EE		  = cms.int32(1),
#                   	       deta_EB		  = cms.double(999999.),
#                   	       dphi_EB		  = cms.double(999999.),
#                   	       sihih_EB		  = cms.double(999999.),
#                   	       hoe_EB		  = cms.double(999999.),
#                   	       d0_EB		  = cms.double(999999.),
#                   	       dZ_EB		  = cms.double(999999.),
#                   	       ooemoop_EB	  = cms.double(999999.),
#                   	       reliso_EB	  = cms.double(999999.),
#                   	       deta_EE		  = cms.double(999999.),
#                   	       dphi_EE		  = cms.double(999999.),
#                   	       sihih_EE		  = cms.double(999999.),
#                   	       hoe_EE		  = cms.double(999999.),
#                   	       d0_EE		  = cms.double(999999.),
#                   	       dZ_EE		  = cms.double(999999.),
#                   	       ooemoop_EE	  = cms.double(999999.),
#                   	       reliso_EE	  = cms.double(999999.),
#			       mHits_EB		  = cms.int32(9999),
#			       mHits_EE		  = cms.int32(9999),
			       vtxFitConv	  = cms.bool(False),
        		       pvSrc  		  = cms.InputTag("offlineSlimmedPrimaryVertices"),
        		       rhoSrc 		  = cms.InputTag("fixedGridRhoFastjetAll"),
                               #cutsToIgnore       = cms.vstring("reliso_EB","reliso_EE")
                               #cutsToIgnore       = cms.vstring("vtxFitConv")
)
