import FWCore.ParameterSet.Config as cms
import os

relBase    = os.environ['CMSSW_BASE']

XConeCalc = cms.PSet(
                      packedPFCandColl_it	 = cms.InputTag("packedPFCandidates"),
                      packedGenParticleColl_it	 = cms.InputTag("packedGenParticles"),
                      XConeR			 = cms.double(0.4),
                      XConeNumJets		 = cms.int32(6),
                      VarNumJets		 = cms.bool(True),
                      XConeBeta			 = cms.double(2.0),
                      usePFchs			 = cms.bool(True),
                      doPUPPI			 = cms.bool(True),
                      doGenXCone		 = cms.bool(True),
                      IsMc				 = cms.bool(False),
                      DEBUG			     = cms.bool(False),
                      saveJetConst		 = cms.bool(False),
                      MCL1JetPar               = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016V3_MC_L1FastJet'),
                      MCL2JetPar               = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016V3_MC_L2Relative'),
                      MCL3JetPar               = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016V3_MC_L3Absolute'),
                      JECunc_txtfile           = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016V3_MC_Uncertainty'),
                      JER_txtfile              = cms.string(relBase+'/src/LJMet/Com/data/Spring16V10/Spring16_25nsV10_MC_PtResolution'),
                      JERSF_txtfile            = cms.string(relBase+'/src/LJMet/Com/data/Spring16V10/Spring16_25nsV10_MC_SF'),
                      DataL1JetPar_BCD             = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016BCDV3_DATA_L1FastJet'),
                      DataL2JetPar_BCD             = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016BCDV3_DATA_L2Relative'),
                      DataL3JetPar_BCD             = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016BCDV3_DATA_L3Absolute'),
                      DataResJetPar_BCD            = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016BCDV3_DATA_L2L3Residual'),
                      DataL1JetPar_EF             = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016EFV3_DATA_L1FastJet'),
                      DataL2JetPar_EF             = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016EFV3_DATA_L2Relative'),
                      DataL3JetPar_EF             = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016EFV3_DATA_L3Absolute'),
                      DataResJetPar_EF            = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016EFV3_DATA_L2L3Residual'),
                      DataL1JetPar_G             = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016GV3_DATA_L1FastJet'),
                      DataL2JetPar_G             = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016GV3_DATA_L2Relative'),
                      DataL3JetPar_G             = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016GV3_DATA_L3Absolute'),
                      DataResJetPar_G            = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016GV3_DATA_L2L3Residual'),
                      DataL1JetPar_H             = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016HV3_DATA_L1FastJet'),
                      DataL2JetPar_H             = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016HV3_DATA_L2Relative'),
                      DataL3JetPar_H             = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016HV3_DATA_L3Absolute'),
                      DataResJetPar_H            = cms.string(relBase+'/src/LJMet/Com/data/Summer16RRV3/Summer16_23Sep2016HV3_DATA_L2L3Residual'),
                      JECup			     = cms.bool(False),
                      JECdown			 = cms.bool(False),
                      JERup			     = cms.bool(False),
                      JERdown			 = cms.bool(False),
                      )
